/*
Please refer to readme.html for full Instructions

Text[...]=[title,text]

Style[...]=[TitleColor,TextColor,TitleBgColor,TextBgColor,TitleBgImag,TextBgImag,TitleTextAlign,TextTextAlign, TitleFontFace, TextFontFace, TipPosition, StickyStyle, TitleFontSize, TextFontSize, Width, Height, BorderSize, PadTextArea, CoordinateX , CoordinateY, TransitionNumber, TransitionDuration, TransparencyLevel ,ShadowType, ShadowColor]
*/
var FiltersEnabled = 1 // if your not going to use transitions or filters in any of the tips set this to 0
 var t0 ="<span class='head2'>Электрическая цепь</span> - это совокупность устройств и объектов, образующих путь для электрического тока, электромагнитные процессы в которых могут быть описаны с помощью понятий об электродвижущей силе, токе и напряжении."
 var t1 ="<span class='text'><span class='head2'>Электрический ток проводимости</span> - явление направленного движения свободных носителей электрического заряда <span class='index'>q</span> в веществе или в вакууме, количественно характеризуемое скалярной величиной, равной производной по времени от электрического заряда, переносимого свободными носителями заряда сквозь рассматриваемую поверхность, т. е. </span><table width='100%' border='0'>  <tr>    <td height='30'><div align='left' class='text'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong><img width='160' height='36' src='page11/clip_image002_0000.jpg'></strong></div></td>"+
"<td class='head2'><div align='right' class='head2'>(1.1)</div></td></tr></table><span class='text'>Из выражения (1.1) получим единицу тока [ <span class='index'>I</span> ] = [<span class='index'> q</span> ]/[ <span class='index'>t</span> ] = Кл/c = A&#183;c/c = A (ампер). </p>"
  var t2 ="<p class='text'><span class='head2'>Электрический ток переноса</span>  – электрический ток, осуществляемый переносом электрических зарядов телами, количественно характеризуемый скалярной величиной, равной производной по времени от электрического заряда, переносимого телами сквозь рассматриваемую поверхность.</p>"
   var t3 ="<span class='head2'>Электрический ток смещения</span> – совокупность электрического тока смещения в пустоте и электрического тока поляризации диэлектрика, количественно характеризуемая скалярной величиной, равной производной по времени от потока электрического смещения <span class='index'>DS</span> сквозь рассматриваемую поверхность <span class='index'>S</span>, т. е.   <img src='page11/clip_image002_0001.jpg' width='202' height='36' align='top'><br>где <span class='index'>D </span>- электрическое смещение.</p>"
    var t4 ="<p class='text'><span class='head2'>Полный электрический ток</span> –  скалярная величина, равная сумме электрического тока проводимости, электрического тока переноса и электрического тока смещения сквозь рассматриваемую поверхность.</p>"
	 var t5 ="<p class='text'><span class='head2'>Постоянный электрический ток</span> (в дальнейшем <span class='head2'>ток</span>) - это неизменное и однонаправленное движение заряженных частиц (зарядов). При постоянном токе в течение каждого одинакового промежутка  времени    <span class='symbol'>D</span><span class='index'>t </span>переносится  одинаковый заряд  <span class='symbol'>D</span><span class='index'>q</span>. Поэтому ток   <span class='index'>i</span> = <span class='index'>q</span>/<span class='index'>t</span>, где <span class='index'>q</span> - весь заряд  в кулонах (Кл) за  время <span class='index'>t</span> (с). </p>"
	 var t6 ="<span class='text'><span class='head2'>Условное положительное направление тока</span><span class='index'> I</span> во внешней (от источника энергии) цепи противоположно направлению движения потока электронов (электрон - частица, обладающая наименьшим отрицательным зарядом (<span class='index'>q</span><span class='indexsmall'>e</span> = -1,602<span class='symbol'>Ч</span>10<span class='stepen'>-19</span> Кл, тогда 1Кл = 6,24<span class='symbol'>Ч</span>10<span class='stepen'>18</span>  электронов)), т. е. он протекает от точки с большим потенциалом к точке с меньшим потенциалом, вызывая <span class='head2'>падение напряжения</span> (в дальнейшем <span class='head2'>напряжение</span>) на сопротивлении этого участка, т. е.</span><table width='100%'  border='0'><tr>    <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class='index'>U</span><span class='indexsmall'>ab</span> = <span class='symbol'>j</span><span class='indexsmall'>a</span> - <span class='symbol'>j</span><span class='indexsmall'>b</span>.</td>"+
	 "<td><div align='right'><span class='head2'>(1.2)</span></div></td>  </tr></table>"
	 	 var t7 ="<span class='text'><span class='head2'>Потенциал электрический</span> (<span class='symbol'>j</span><span class='indexsmall'>a</span></a>) точки <span class='index'>а</span> - работа, которую нужно выполнить, чтобы перенести единицу заряда (1&nbsp;Кл)  из данной точки в бесконечность (где нет электрического поля ), т. е.</span><table width='100%'  border='0'>  <tr>    <td>&nbsp;&nbsp;&nbsp;<img src='page11/clip_image002_0007.gif' width='164' height='69'><img src='page11/clip_image002_0008.gif' width='99' height='68'></td>    <td><div align='right'><span class='head2'>(1.3)</span></div></td>  </tr></table>"+
"<span class='text'>где  <img src='page11/clip_image002_0006.gif' width='18' height='23' align='absmiddle'>   - <span class='head2'>напряжённость</span> (вектор) электрического поля, численно равная отношению силы, действующей на заряженную частицу, к значению её заряда. Из этого определения получают единицу напряжённости<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [<span class='index'>E</span>] = [H]/[Кл] = В<span class='symbol'>Ч</span>А<span class='symbol'>Ч</span>с/м<span class='symbol'>Ч</span>A<span class='symbol'>Ч</span>c = В/м (вольт на метр). </span>"
		 	 var t8 ="<span class='text'><span class='head2'>Напряжение</span> - это работа, затрачиваемая на перенос единицы заряда (1&nbsp;Кл) из точки <span class='index'>а</span> в точку <span class='index'>b</span> поля с напряжённостью<img src='page11/clip_image002_0006.gif' width='18' height='23' align='absmiddle'>по произвольному пути и равная линейному интегралу напряженности электрического поля, т. е.</span><table width='100%'  border='0'>  <tr>    <td>&nbsp;&nbsp;&nbsp;<img src='page11/clip_image002_0009.gif' width='99' height='49' align='middle'>.</td>    <td><div align='right'><span class='head2'>(1.3)</span></div></td>  </tr></table><span class='text'>Однозначно определяют только<span class='head2'> разность потенциалов (напряжение)</span> между соответствующими точками. Когда говорят о потенциале точки электрической цепи, то подразумевают разность потенциалов между этой точкой и другой (обычно заземлённой), потенциал которой принимают равным нулю. Из определения (1.4) получают единицу напряжения (потенциала) <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[<span class='index'>U</span>] = [В/м]<span class='symbol'>Ч</span>[м] = B (вольт). </span>"
   var t9 ="<p class='text'><span class='head2'>Электродвижущая сила</span> <span class='index'>E</span> (в дальнейшем ЭДС <span class='index'>E</span>) - скалярная величина, характеризующая способность стороннего поля и индуктированного электрического поля вызывать электрический ток. ЭДС <span class='index'>Е</span> численно равна работе (энергии) <span class='index'>W</span> в джоулях (Дж), затрачиваемой этим полем на перемещение единицы заряда (1 Кл) из одной точки поля в другую.  Из этого определения получим единицу ЭДС [<span class='index'>E</span>] = [<span class='index'>W</span>]/[<span class='index'>q</span>] = Дж/Кл = В&#183;А&#183;с/А&#183;с = В (вольт). Тогда <span class='head2'>напряжение</span> (разность потенциалов) 1 В равно 1 Дж энергии для перемещения 1 Кл заряда  из одной точки проводника в другую.</p>"

Text[0]=[":: Электрическая цепь ::",t0]
Text[1]=[":: Электрический ток проводимости ::",t1]
Text[2]=[":: Электрический ток переноса ::",t2]
Text[3]=[":: Электрический ток смещения ::",t3]
Text[4]=[":: Полный электрический ток ::",t4]
Text[5]=[":: Постоянный электрический ток ::",t5]
Text[6]=[":: Условное положительное направление тока ::",t6]
Text[7]=[":: Потенциал электрический ::",t7]
Text[8]=[":: Напряжение ::",t8]
Text[9]=[":: Электродвижущая сила  (ЭДС) ::",t9]

Style[0]=["white","black","black","white","","","center","","","Verdana","center","",2,2,"100%",,1,5,0,10,51,1,,"complex","gray"]

applyCssFilter()

